-- Run this SQL in the Supabase SQL editor before enabling the app integration.

create table if not exists public.pension_calculations (
    id bigint generated by default as identity primary key,
    date_of_birth date not null,
    retirement_date date not null,
    age_next_birthday integer not null,
    purchase_factor numeric(10, 4) not null,
    effective_policy_date text not null,
    restoration_date date not null,
    age_at_restoration text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.app_visits (
    id text primary key,
    total_visits bigint not null default 0,
    updated_at timestamptz not null default now()
);

alter table public.pension_calculations enable row level security;
alter table public.app_visits enable row level security;

create or replace function public.increment_app_visit(counter_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    next_total bigint;
begin
    insert into public.app_visits as visits (id, total_visits, updated_at)
    values (counter_id, 1, now())
    on conflict (id) do update
        set total_visits = visits.total_visits + 1,
            updated_at = now()
    returning total_visits into next_total;

    return next_total;
end;
$$;

grant execute on function public.increment_app_visit(text) to anon;

create policy "Allow public calculation inserts"
    on public.pension_calculations
    for insert
    to anon
    with check (true);

create policy "Allow public visit reads"
    on public.app_visits
    for select
    to anon
    using (true);

create policy "Allow public visit inserts"
    on public.app_visits
    for insert
    to anon
    with check (true);

create policy "Allow public visit updates"
    on public.app_visits
    for update
    to anon
    using (true)
    with check (true);
